### PR TITLE
Added NS Usage Description in ProjectOxfordFace-Info.plist

### PR DESCRIPTION
**Pull request by ravimandal47**
Added usage description for camera and photo library access. The app is crashing in iOS 10.

### CODE REVIEW

**Comment by huxuan** [comment]
Hi @ravimandal47, thanks for your interest and sorry for the late reply. Actually we are preparing for the new release and this bug should have been fixed by pull request #10, which is supposed to be merged after the service update deployment.

**Comment by ravimandal47** [comment]
Hi @huxuan, thanks for the response. Does it mean that I should close the PR ?

**Comment by huxuan** [comment]
Hi @ravimandal47, I am afraid so. I really appreciate your efforts and hope you enjoy the Cognitive Services - Face API. Feel free to reach me if there is any further problem.

**Comment by ravimandal47** [comment]
No problem @huxuan . I am closing this pull request.

**Pull request closed without merging**
